name: Compatibility Test for `codepen-fetcher`

on:
  # schedule:
  #   - cron: '0 1 * * 1' # Every Monday at 9 AM (UTC+8)
  # workflow_dispatch:
  # workflow_call:
  push:
    branches:
      - test-ci

jobs:
  test-node:
    name: Test on Node ${{ matrix.node_version }}
    strategy:
      fail-fast: false
      matrix:
        node_version: ['16', '18', '20', '22', '24']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: node -v
      - name: Install `codepen-fetcher`
        run: |
          npm install codepen-fetcher --no-save
          echo "Installed version: "
          node -p "require('codepen-fetcher/package.json').version"
      - run: node index.js
